export const GET_SEARCH_ID = "GET_SEARCH_ID";
export const GET_SEARCH_ID_SUCCESS = "GET_SEARCH_ID_SUCCESS";
export const SET_STATUS = "SET_STATUS";
export const SET_FILTER_NUMBER_STOPS = "SET_FILTER_NUMBER_STOPS";
